//app-config.js - generated by MarkLogic Appbuilder 2.0 2013-05-06T16:33:33.992476-04:00
var sidebar_config =
{
  "facets": {
    "award": {
      "name": "award",
      "type": "range",
      "options": {
        "order": "",
        "direction": "",
        "limit": "10"
      },
      "label": {
        "lang": "en",
        "_value": "Award"
      },
      "front-page": "false",
      "side-bar": "true",
      "datatype": {
        "collation": "http:\/\/marklogic.com\/collation\/",
        "_value": "xs:string"
      },
      "qnames": {
        "type": "element\/attribute",
        "elem-ns": "http:\/\/marklogic.com\/wikipedia",
        "elem": "nominee",
        "attr-ns": "",
        "attr": "award",
        "field": ""
      },
      "fragment-scope": "",
      "collection-prefix": "",
      "facet": {
        "enabled": "true",
        "_value": "\n            ",
        "options": {
          "order": "",
          "direction": "",
          "limit": "10"
        }
      },
      "term-options": {
        "case": "",
        "punct": "punctuation-insensitive",
        "wild": "",
        "stem": "",
        "diacritic": ""
      },
      "relative-buckets": {
        "use": "false",
        "bucket": [
          {
            "anchor": "",
            "lt": "",
            "ge": "",
            "name": ""
          }
        ],
        "_value": "\n            "
      },
      "absolute-buckets": {
        "use": "false",
        "bucket": [
          {
            "anchor": "",
            "lt": "",
            "ge": "",
            "name": ""
          }
        ],
        "_value": "\n            "
      }
    },
    "centroid": {
      "name": "centroid",
      "type": "geospatial",
      "options": {
        "order": "frequency-order",
        "direction": "descending",
        "limit": "10000"
      },
      "fragment-scope": "",
      "label": "Centroid",
      "front-page": "false", "side-bar": "false", "datatype": {"collation": "", "_value": "xs:"}, "qnames": {"type": "element\/attribute", "elem-ns": "http:\/\/where.yahooapis.com\/v1\/schema.rng", "elem": "centroid", "attr-ns": "", "attr": "", "field": ""}, "collection-prefix": "", "facet": {"enabled": "true", "_value": "\n\t\t\t", "options": {"order": "frequency-order", "direction": "descending", "limit": "10000"}}, "term-options": {"case": "", "punct": "punctuation-insensitive", "wild": "", "stem": "", "diacritic": ""}, "absolute-buckets": {"use": "false", "bucket": [
  {"anchor": "", "lt": "", "ge": "", "name": ""}
], "_value": "\n\t\t\t"}, "relative-buckets": {"use": "false", "bucket": [
  {"anchor": "", "lt": "", "ge": "", "name": ""}
], "_value": "\n\t\t\t"}, "geotype": "geospatial-element-pair-index", "parentlocalname": "centroid", "parentnamespaceuri": "http:\/\/where.yahooapis.com\/v1\/schema.rng", "latitudelocalname": "latitude", "latitudenamespaceuri": "http:\/\/where.yahooapis.com\/v1\/schema.rng", "longitudelocalname": "longitude", "longitudenamespaceuri": "http:\/\/where.yahooapis.com\/v1\/schema.rng", "localname": "", "namespaceuri": ""}, "decade": {"name": "decade", "type": "range", "options": {"order": "", "direction": "", "limit": "10"}, "label": {"lang": "en", "_value": "Decade"}, "front-page": "false", "side-bar": "true", "datatype": {"collation": "", "_value": "xs:gYear"}, "qnames": {"type": "element\/attribute", "elem-ns": "http:\/\/marklogic.com\/wikipedia", "elem": "nominee", "attr-ns": "", "attr": "year", "field": ""}, "fragment-scope": "", "collection-prefix": "", "facet": {"enabled": "true", "_value": "\n            ", "options": {"order": "", "direction": "", "limit": "10"}}, "term-options": {"case": "", "punct": "punctuation-insensitive", "wild": "", "stem": "", "diacritic": ""}, "relative-buckets": {"use": "false", "bucket": [
  {"anchor": "", "lt": "", "ge": "", "name": ""}
], "_value": "\n            "}, "absolute-buckets": {"use": "true", "bucket": [
  {"ge": "2000", "name": "2000s", "_value": "2000s"},
  {"ge": "1990", "lt": "2000", "name": "1990s", "_value": "1990s"},
  {"ge": "1980", "lt": "1990", "name": "1980s", "_value": "1980s"},
  {"ge": "1970", "lt": "1980", "name": "1970s", "_value": "1970s"},
  {"ge": "1960", "lt": "1970", "name": "1960s", "_value": "1960s"},
  {"ge": "1950", "lt": "1960", "name": "1950s", "_value": "1950s"},
  {"ge": "1940", "lt": "1950", "name": "1940s", "_value": "1940s"},
  {"ge": "1930", "lt": "1940", "name": "1930s", "_value": "1930s"},
  {"lt": "1930", "name": "1920s", "_value": "1920s"}
], "_value": "\n            "}}, "win": {"name": "win", "type": "range", "options": {"order": "", "direction": "", "limit": "10"}, "label": {"lang": "en", "_value": "Winners"}, "front-page": "false", "side-bar": "true", "datatype": {"collation": "http:\/\/marklogic.com\/collation\/", "_value": "xs:string"}, "qnames": {"type": "element\/attribute", "elem-ns": "http:\/\/marklogic.com\/wikipedia", "elem": "nominee", "attr-ns": "", "attr": "winner", "field": ""}, "fragment-scope": "", "collection-prefix": "", "facet": {"enabled": "true", "_value": "\n            ", "options": {"order": "", "direction": "", "limit": "10"}}, "term-options": {"case": "", "punct": "punctuation-insensitive", "wild": "", "stem": "", "diacritic": ""}, "relative-buckets": {"use": "false", "bucket": [
  {"anchor": "", "lt": "", "ge": "", "name": ""}
], "_value": "\n            "}, "absolute-buckets": {"use": "false", "bucket": [
  {"anchor": "", "lt": "", "ge": "", "name": ""}
], "_value": "\n            "}}, "name": {"name": "name", "type": "range", "options": {"order": "frequency-order", "direction": "descending", "limit": "10"}, "label": {"lang": "en", "_value": "People"}, "front-page": "true", "side-bar": "false", "datatype": {"collation": "http:\/\/marklogic.com\/collation\/", "_value": "xs:string"}, "qnames": {"type": "element\/attribute", "elem-ns": "http:\/\/marklogic.com\/wikipedia", "elem": "name", "attr-ns": "", "attr": "", "field": ""}, "fragment-scope": "", "collection-prefix": "", "facet": {"enabled": "true", "_value": "\n            ", "options": {"order": "frequency-order", "direction": "descending", "limit": "10"}}, "term-options": {"case": "", "punct": "punctuation-insensitive", "wild": "", "stem": "", "diacritic": ""}, "relative-buckets": {"use": "false", "bucket": [
  {"anchor": "", "lt": "", "ge": "", "name": ""}
], "_value": "\n            "}, "absolute-buckets": {"use": "false", "bucket": [
  {"anchor": "", "lt": "", "ge": "", "name": ""}
], "_value": "\n            "}}, "film": {"name": "film", "type": "range", "options": {"order": "frequency-order", "direction": "descending", "limit": "10"}, "label": {"lang": "en", "_value": "Films"}, "front-page": "true", "side-bar": "false", "datatype": {"collation": "http:\/\/marklogic.com\/collation\/", "_value": "xs:string"}, "qnames": {"type": "element\/attribute", "elem-ns": "http:\/\/marklogic.com\/wikipedia", "elem": "film-title", "attr-ns": "", "attr": "", "field": ""}, "fragment-scope": "", "collection-prefix": "", "facet": {"enabled": "true", "_value": "\n            ", "options": {"order": "frequency-order", "direction": "descending", "limit": "10"}}, "term-options": {"case": "", "punct": "punctuation-insensitive", "wild": "", "stem": "", "diacritic": ""}, "relative-buckets": {"use": "false", "bucket": [
  {"anchor": "", "lt": "", "ge": "", "name": ""}
], "_value": "\n            "}, "absolute-buckets": {"use": "false", "bucket": [
  {"anchor": "", "lt": "", "ge": "", "name": ""}
], "_value": "\n            "}}}}


var results_config =
{"metadata": {"columns": [
  {"abstract-title": [
    {"position": "1", "type": "value", "elem": "name", "attr": ""},
    {"position": "2", "type": "literal", "text": "\n                 \"\n            "},
    {"position": "3", "type": "value", "elem": "film-title", "attr": ""},
    {"position": "4", "type": "literal", "text": "\n                \"\n            "}
  ], "abstract-metadata": [
    {"position": "1", "type": "value", "elem": "nominee", "attr": "award"},
    {"position": "2", "type": "literal", "text": "\n                 - \n            "},
    {"position": "3", "type": "value", "elem": "nominee", "attr": "year"}
  ]}
], "sort": {"relevance": {"position": "1", "label": {"lang": "en", "_value": "Relevance"}, "order": {"direction": "descending", "type": "score", "datatype": "", "collation": "", "elem-ns": "", "elem": "", "attr-ns": "", "attr": ""}}, "year": {"position": "2", "label": {"lang": "en", "_value": "Year"}, "order": {"direction": "descending", "type": "score", "datatype": "", "elem-ns": "", "elem": "", "attr-ns": "", "attr": ""}}}}}


var controller_config = {
  appWrapper: "body",
  widgetClass: ".widget",
  version: "v1", // version number of the REST API
  proxy: false, // proxy url - defaults to false for no proxy
  optionsNode: "all",
  queryPage: 1,
  pageLength: 10,
  useShadows: true, // global toggle for shadow queries
  enableBookmarking: true, // toggle for bookmarking suppport
  bookmarkingDelimiters: ["*_*", "*__*"] // delimiters to be used while encoding url bookmarks
}
var bar_config_1 = { constraint: "award", constraintType: "range-unbucketed", dataType: "xs:string", title: "Awards", dataLabel: null, measureLabel: null };
var pie_config_2 = { constraint: "name", constraintType: "range-unbucketed", dataType: "xs:string", title: "People", dataLabel: null, measureLabel: null };





